### ISSUE TITLE
After truncate, the hdfs file still exists

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/byconity-docker#3]
server application log
![mmexport1673423324319](https://user-images.githubusercontent.com/50901800/211748987-368f28e1-1a06-45ce-b902-0458694a7745.png)

Linux 93861685cbd4 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 GNU/Linux

Debian GNU/Linux 9

truncate table helloworld.my_first_table;

**Comment by canhld94** [comment]
Hi @zhbdesign, can you send me the full server log file? The log here indicates that hdfs operations failed, but we need the full log to find the root cause. Thanks.
