### ISSUE TITLE
occurred

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/byconity-docker#4]
2023.01.11 08:59:07.300901 [ 43 ] {} <Error> TxnGCThread: Error occurs during daemon TxnGCThread execution: Code: 439, e.displayText() = DB::Exception: Cannot schedule a task: no free thread (timeout=0) (threads=16, jobs=16) SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::Exception::Exception<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long&>(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long&&, unsigned long&) @ 0xb26bc72 in /opt/byconity/usr/bin/clickhouse
3. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>)::'lambda'(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const @ 0xb26c6de in /opt/byconity/usr/bin/clickhouse
4. void ThreadPoolImpl<ThreadFromGlobalPool>::scheduleImpl<void>(std::__1::function<void ()>, int, std::__1::optional<unsigned long>) @ 0xb26820b in /opt/byconity/usr/bin/clickhouse
5. ThreadPoolImpl<ThreadFromGlobalPool>::scheduleOrThrow(std::__1::function<void ()>, int, unsigned long) @ 0xb269926 in /opt/byconity/usr/bin/clickhouse
6. DB::DaemonManager::DaemonJobTxnGC::cleanTxnRecords(std::__1::vector<DB::TransactionRecord, std::__1::allocator<DB::TransactionRecord> > const&) @ 0x154af26c in /opt/byconity/usr/bin/clickhouse
7. DB::

**Comment by canhld94** [comment]
Hi, thank you for trying out Byconity and giving feedback!

This exception means the daemon manager doesn't have enough threads to schedule all background tasks. It should push the task to the waiting queue but for some reason, it throws an exception. We will look at it issue.

Thank you.

**Comment by canhld94** [comment]
Close as solved
