### ISSUE TITLE
resource-manager-0 error

### ISSUE THREAD

**Issue by zhbdesign** [ByConity/byconity-docker#7]
The cluster is started using docker-compose.yml.multiworkers. The following error log appears after the resource-manager-0 container is started.

2023.01.29 08:10:56.358771 [ 1 ] {} <Error> ElectionController: Code: 49, e.displayText() = DB::Exception: Worker group wg_default already exists in VW vw_default SQLSTATE: HY000, Stack trace (when copying this message, always include the lines below):

0. Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x18e345d2 in /opt/byconity/usr/bin/clickhouse
1. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xb230820 in /opt/byconity/usr/bin/clickhouse
2. DB::ResourceManagement::VirtualWarehouse::addWorkerGroup(std::__1::shared_ptr<DB::ResourceManagement::IWorkerGroup> const&, bool) @ 0x135dc005 in /opt/byconity/usr/bin/clickhouse
3. DB::ResourceManagement::ResourceManagerController::initialize() @ 0x135c17da in /opt/byconity/usr/bin/clickhouse
4. DB::ResourceManagement::ElectionController::pullState() @ 0x135c6e80 in /opt/byconity/usr/bin/clickhouse
5. DB::ResourceManagement::ElectionController::onLeader() @ 0x135c6866 in /opt/byconity/usr/bin/clickhouse
6. DB::ResourceManagement::ElectionController::ElectionController(DB::ResourceManagement::ResourceManagerController&) @ 0x135c613f in /opt/byconity/usr/bin/clickhouse
7. DB::ResourceManagement::ResourceManagerController::ResourceManagerController(std::__1::shared_ptr<DB::Context const>) @ 0x135ba938 in /opt/byconity/usr/bin/clickhouse
8. DB::ResourceManager::main(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) @ 0x135a8896 in /opt/byconity/usr/bin/clickhouse
9. Poco::Util::Application::run() @ 0x18dbfcaa in /opt/byconity/usr/bin/clickhouse
10. DB::ResourceManager::run() @ 0x135a7fb5 in /opt/byconity/usr/bin/clickhouse
11. Poco::Util::ServerApplication::run(int, char**) @ 0x18dd1b1b in /opt/byconity/usr/bin/clickhouse
12. mainEntryClickHouseResourceManager(int, char**) @ 0x135aa0eb in /opt/byconity/usr/bin/clickhouse
13. main @ 0xb22aae8 in /opt/byconity/usr/bin/clickhouse
14. __libc_start_main @ 0x2409b in /lib/x86_64-linux-gnu/libc-2.28.so
15. _start @ 0xb22a2ea in /opt/byconity/usr/bin/clickhouse
 (version 21.8.7.1)

**Comment by canhld94** [comment]
Hi @zhbdesign this exception happens during leader change of resource manager and it should not affect the functionality of resource manager.

**Comment by canhld94** [comment]
Close as solved
